# Generated by Django 4.1 on 2024-03-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_manager_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='count_value',
        ),
        migrations.AddField(
            model_name='counter',
            name='count_new_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counter',
            name='count_old_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counter',
            name='pdl_type',
            field=models.CharField(choices=[('ELEC', 'ELEC'), ('GAZ', 'GAZ')], default='ELEC', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_reason', models.CharField(max_length=255)),
                ('company_siret', models.CharField(max_length=14)),
                ('company_postal_code', models.CharField(max_length=20)),
                ('manager_first_name', models.CharField(max_length=50)),
                ('manager_last_name', models.CharField(max_length=50)),
                ('manager_phone_number', models.CharField(max_length=8)),
                ('manager_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manager')),
            ],
        ),
    ]
