# Generated by Django 4.1 on 2024-03-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_counter_count_value_counter_count_new_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='count_new_value',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='count_old_value',
        ),
        migrations.AddField(
            model_name='counter',
            name='count_value',
            field=models.IntegerField(default=0),
        ),
    ]
